### ISSUE TITLE
Build out 'flashcards' page

### ISSUE THREAD

**Issue by katrinars** [katrinars/flashcard-app#5]
should be styled with header and all regular website section, then show the user's flashcard collection

**Comment by katrinars** [comment]
this is on pause for design, you should be able to see the tag on the Projects page a little better than you can in Issues @majesticace

**Comment by katrinars** [comment]
also your commits aren't showing on my end @majesticace

**Comment by majesticace** [comment]
> also your commits aren't showing on my end @majesticace

Noted Thank you, I'll try to fix that now.
